[pytest]
markers =
    math: Math tests
    login: All login tests
    positive: All positive path tests
    negative: All negative path tests
    exceptions: All exceptions path tests
    debug: Use only for one test at time to debug it. No extra reports etc.